<?php

use Symfony\Component\HttpFoundation\Response;

/**
 * Implements hook_jsonapi_response_alter().
 *
 * @param array $jsonapi_response
 *   The decoded JSON data to be altered.
 * @param \Symfony\Component\HttpFoundation\Response $response
 *   The response.
 */
function dw_rest_jsonapi_response_alter(array &$jsonapi_response, Response $response) {
  if (isset($jsonapi_response['data']) && is_array($jsonapi_response['data'])) {
    foreach ($jsonapi_response['data'] as &$item) {
      if (isset($item['relationships']['field_image']) && !empty($item['relationships']['field_image'])) {
        foreach ($item['relationships']['field_image'] as &$image) {
          if (isset($image['id'])) {
            $media_id = $image['meta']['drupal_internal__target_id'];
            $media_entity = \Drupal::entityTypeManager()->getStorage('media')->load($media_id);
            if ($media_entity && $media_entity->hasField('field_media_image')) {
              $file = $media_entity->get('field_media_image')->entity;

              if ($file) {
                $file_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
                $image['url'] = $file_url;
              }
            }
          }
        }
      }
    }
  }
}
