_core:
  default_config_hash: ijfbzDTN4CbE7Sr-6ubWzy_t1vH4OtU1doNCLssVz-4
langcode: en
uuid: 5528e78b-f055-4da1-9347-ae87af463880
name: 'Vue Sphere'
mail: fabricio.lopesx@gmail.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/7
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
